config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
namespace :admin do
  post "search", to: "search#search", as: 'search'
  resources :holes do
    get :hole_images
    post :set_images_rank
  end
  resources :score_cards
  resources :amenities
  resources :networks
  resources :resorts do
    get :courses_list
    get :courses
    get :add_course
  end
  resources :locations
  resources :courses do
    get :holes_list
    get :get_course_images
    post :set_images_rank
  end
  resources :ads
  # resources :videos
  get "users/index"
  get "courses/holes/:id", to: 'courses#holes',as: 'holes_create'
  post "courses/remove_course_image", to: 'courses#remove_course_image'
  post "courses/remove_scorecard_image", to: 'courses#remove_scorecard_image'
  get "/add_playlist_item", to: 'courses#add_playlist_item'
  get "/add_scorecard", to: 'courses#add_scorecard'
  post "videos/create", to: 'videos#create' ,as: 'video_create'
  get "videos/:id" , to: 'videos#show' ,as: 'video'
  post "tags/:video_id/save" ,to: 'tags#create', as: 'create_tag'
  delete "tags/:id" ,to: 'tags#destroy', as: 'delete_tag'
  post "holes/add_image" ,to: 'holes#add_image', as: 'add_image'
  post "holes/add_logo_hyperlink" ,to: 'holes#add_logo_hyperlink', as: 'add_logo_hyperlink'
  post "holes/add_logo_image" ,to: 'holes#add_logo_image', as: 'add_logo_image'
  put "holes/image/:id" ,to: 'holes#remove_image', as: 'remove_image'
  put "holes/logo_image/:id" ,to: 'holes#remove_logo_image', as: 'remove_logo_image'
  post "holes/add_map" ,to: 'holes#add_map', as: 'add_map'
  put "holes/map/:id" ,to: 'holes#remove_map', as: 'remove_map'
  post "holes/add_hole_image" ,to: 'holes#add_hole_image', as: 'add_hole_image'
  delete "holes/gallery/:id" ,to: 'holes#remove_hole_image', as: 'remove_hole_image'
  post "ads/add_image" ,to: 'ads#add_image', as: 'upload_image'
  post "holes/add_yardages" ,to: 'holes#add_yardages', as: 'add_yardages'
  get "/get_yardages", to: 'holes#get_yardages', as: 'get_hole_yardages'
  delete "videos/:id" ,to: 'videos#destroy', as: 'delete_video'
  post "courses/:course_id/update_holes", to: "courses#update_holes", as: 'update_holes_details'
end

  devise_for :admins
  devise_for :users
  # put '/users', :to => 'devise/registrations#update', :as => :update_user
  namespace :v1, defaults: {format: :json} do
    delete '/sessions', :to => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :registrations, only: [:create]
    resources :pages, only: [:index]
    resources :courses, only:[:index,:show]
    resources :users, only:[:show, :update]
    resources :videos, only:[:show]
    resources :lists, only: [:create, :show]
    resources :reviews, only: [:show]
    resources :scores, only: [:create, :show]
    post "lists/:id/add_course", to: 'lists#add_course', as: 'add_course'
    post "courses/:id/add_user", to: 'courses#add_user', as: 'add_user'
    get "users/:id/lists" , to: 'users#lists', as: 'user_lists'
  end

  root to: "admin/courses#new"

  namespace :embed do
    # resources :pages, only: :show, path: "" # -> domain.com/embed/1
    get "show/:id", to: 'pages#show'
    get ":id", to: 'pages#display',as: 'display_info'
    get "dis2/:id", to: 'pages#dis2'
    get "hole/:id", to: 'pages#hole_by_hole',as: 'hole_info'
    get "course/:id", to: 'pages#course_home',as: 'course_info'
    post "pages/update_tee_scorecard", to: 'pages#update_tee_scorecard'
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/hole.rb
class Hole < ApplicationRecord
    belongs_to :course
    # validates :par,:yards, :mhcp, :whcp, presence: true
    has_one :video, as: :videoable
    has_one :score
    has_many :ads
    has_many :yardages, :dependent => :destroy
    has_many :pars, :dependent => :destroy
    has_many :hcps, :dependent => :destroy
    has_many :hole_images, :dependent => :destroy


    accepts_nested_attributes_for :yardages, :allow_destroy => true


    has_attached_file :image, styles: {
     thumb: '100x100>',
     square: '200x200#',
     medium: '300x300>'
   }

   has_attached_file :map, styles: {
     thumb: '100x100>',
     square: '200x200#',
     medium: '300x300>'
   }
   has_attached_file :logo_image, styles: {
     thumb: '100x100>',
     square: '200x200#',
     medium: '300x300>'
   }

   # Validate the attached image is image/jpg, image/png, etc
   validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   validates_attachment_content_type :map, :content_type => /\Aimage\/.*\Z/
   validates_attachment_content_type :logo_image, :content_type => /\Aimage\/.*\Z/

  def total_yards
    first_scorecard = course_first_scorecard
    if first_scorecard
      self.yardages.find_by(score_card_id: first_scorecard.id).try(:yards)
      #self.yardages.pluck(:yards).compact.sum
    end
  end

  def total_pars
    first_scorecard = course_first_scorecard
    if first_scorecard
      self.pars.find_by(score_card_id: first_scorecard.id).try(:par)
      #self.pars.pluck(:par).compact.sum
    end
  end

  def total_hcps
    first_scorecard = course_first_scorecard
    if first_scorecard
      self.hcps.find_by(score_card_id: first_scorecard.id).try(:hcp)
      #self.hcps.pluck(:hcp).compact.sum
    end
  end

  def course_first_scorecard
    first_scorecard = self.course.score_cards.order(:rank).first unless self.course.score_cards.pluck(:rank).compact.blank?
    first_scorecard = self.course.score_cards.first if first_scorecard.nil?
    first_scorecard 
  end
end

app/controllers/admin/holes_controller.rb
class Admin::HolesController < ApplicationController
  before_action :set_hole, only: [:show, :edit, :update, :destroy, :remove_image, :remove_map, :remove_logo_image, :hole_images]

  # GET /holes
  # GET /holes.json
  def index
    @holes = Hole.all
  end

  # GET /holes/1
  # GET /holes/1.json
  def show
  end

  # GET /holes/new
  def new
    @hole = Hole.new
  end

  # GET /holes/1/edit
  def edit
  end

  # POST /holes
  # POST /holes.json
  def create
    @hole = Hole.new(hole_params)

    respond_to do |format|
      if @hole.save
        format.html { redirect_to @hole, notice: 'Hole was successfully created.' }
        format.json { render :show, status: :created, location: @hole }
      else
        format.html { render :new }
        format.json { render json: @hole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holes/1
  # PATCH/PUT /holes/1.json
  def update
    respond_to do |format|
      if @hole.update(hole_params)
        format.html { redirect_to @hole, notice: 'Hole was successfully updated.' }
        format.json { render :show, status: :ok, location: @hole }
      else
        format.html { render :edit }
        format.json { render json: @hole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holes/1
  # DELETE /holes/1.json
  def destroy
    @hole.destroy
    respond_to do |format|
      format.html { redirect_to admin_holes_url, notice: 'Hole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_logo_hyperlink
    if params[:copy_all] == "true"
      Hole.joins(:course).where(courses: {id: params[:course_id]}).map{|h| h.logo_hyperlink = params[:hyperlink]; h.save}
    else
      @hole = Hole.find(params[:hole_id])
      @hole.logo_hyperlink = params[:hyperlink]
      @hole.save
    end
    render :json => {status: 'success'}, :layout => false
  end

  def add_logo_image
    @hole = Hole.find(params[:hole][:hole_id])

    if @hole.update(hole_params)
      redirect_to admin_course_path(@hole.course), notice: 'Image was successfully uploaded.'
    else
      redirect_to admin_course_path(@hole.course), notice: 'Image not uploaded.'
    end
  end

  def remove_logo_image
    @hole.logo_image.destroy
    respond_to do |format|
      format.html { redirect_to :back , notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_image
    @hole = Hole.find(params[:hole][:hole_id])
    if @hole.update(hole_params)
      redirect_to admin_course_path(@hole.course), notice: 'Image was successfully uploaded.'
    else
      redirect_to admin_course_path(@hole.course), notice: 'Image not uploaded.'
    end
  end

  # put /holes/1
  # put /holes/1.json
  def remove_image
    @hole.image.destroy
    @hole.update(image: nil)
    respond_to do |format|
      format.html { redirect_to :back , notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_map
    @hole = Hole.find(params[:hole][:hole_id])

    if @hole.update(hole_params)
      redirect_to admin_course_path(@hole.course), notice: 'Map was successfully uploaded.'
    else
      redirect_to admin_course_path(@hole.course), notice: 'Map not uploaded.'
    end
  end

  # put /holes/1
  # put /holes/1.json
  def remove_map
    @hole.map.destroy
    @hole.update(map: nil)
    respond_to do |format|
      format.html { redirect_to :back , notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_yardages
    @hole = Hole.find(params[:yardages][:hole_id])

    @hole.course.score_cards.each do |tees|
      if @hole.yardages.where(score_card_id: tees.id).present?
        @hole.yardages.where(score_card_id: tees.id).first.update(yards: params[:yardages][:"#{tees.id}".to_sym])
        # redirect_to :back, notice: 'Tees yards successfully updated.'
      else
        @yard = @hole.yardages.new
        @yard.score_card_id = tees.id
        @yard.yards = params[:yardages][:"#{tees.id}".to_sym]
        @yard.save
      end
    end
    # if @hole.update(hole_params)
      redirect_to :back, notice: 'Tees yards successfully uploaded.'
    # else
    #   redirect_to admin_course_path(@hole.course), notice: 'Map not uploaded.'
    # end
  end

  def add_hole_image
    @hole = Hole.find(params[:hole][:hole_id])

    # if @hole.update(hole_params)
    if @hole.present?  
      if params[:images]
        params[:images].each { |image|
          @hole.hole_image.create(image: image)
        }
        redirect_to admin_course_path(@hole.course), notice: 'Images were successfully uploaded.'
      end
        
    else
        redirect_to admin_course_path(@hole.course), notice: 'Images not uploaded.'
    end
  end

  # put /holes/1
  # put /holes/1.json
  def remove_hole_image
    @holeimage = HoleImage.find(params[:id])
    @hole=@holeimage.hole
    if @holeimage.destroy
      respond_to do |format|
        format.html { redirect_to :back , notice: 'Gallery image was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  end

  def get_yardages
    @hole = Hole.find(params[:hole_id])
    @score_cards = @hole.course.score_cards
    @yardages = @hole.yardages.where(score_card_id: @score_cards.pluck(:id))
  end

  def hole_images
    @hole_images = @hole.hole_images    
  end

  def set_images_rank
    params[:hole_image].each do |hole_image_id, rank|
      hole_image = HoleImage.find(hole_image_id)
      hole_image.update(rank: rank)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hole
      @hole = Hole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hole_params
      params.require(:hole).permit(:par, :yards, :mhcp, :whcp, :image, :map, :logo_image)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yard_params
      params.require(:yardages).permit!
    end

end

app/helpers/holes_helper.rb
module HolesHelper
end

app/views/admin/holes/_form.html.erb
<div class="form-group"><%= hole.text_field :par, class:"col-md-12 hole-field form-control", placeholder: "Par" %></div>
<div class="form-group"><%= hole.text_field :yards, class:"col-md-12 hole-field form-control", placeholder: "Yards" %></div>
<div class="form-group"><%= hole.text_field :mhcp, class:"col-md-12 hole-field form-control", placeholder: "Men HCP" %></div>
<!-- <div class="form-group"><%#= hole.text_field :whcp, class:"col-md-12 hole-field form-control", placeholder: "Women HCP"%></div> -->
<div class="form-group"><%= hole.text_field :description, class:"col-md-12 hole-field form-control", placeholder: "Description"%></div>

<%= hole.hidden_field :hole_num, value: hole_num%>

app/views/admin/holes/_gallery.html.erb
<div class="row" style="margin-top:10px;">
	<%= form_for :hole_images, url: admin_hole_set_images_rank_path(hole), method: "post", :remote => true do |f| %>
		<% hole.hole_images.order(:rank).each_with_index do | holeimage, index | %>
			<div class="col-md-3 gallery_list">
				<%= hidden_field_tag "hole_image[#{holeimage.id}]", holeimage.rank.present? ? holeimage.rank : index+1, class: "rank-field" %>
				<div class="ordering_buttons">
				  <%= link_to "", "javascript:void(0)", class: "btn btn-xs btn-primary glyphicon glyphicon-chevron-left hole_image-reorder-left" %>
				  <%= link_to "", "javascript:void(0)", class: "btn btn-xs btn-primary glyphicon glyphicon-chevron-right hole_image-reorder-right" %>
				</div>
			    <div class="thumbnail">
			      <a href="javascript:void(0)">
			        <%=image_tag holeimage.image.url(:thumb) %>
			      </a>
			    </div>
			    <div class="col-md-3">
			    	<%= link_to 'Delete', admin_remove_hole_image_path(holeimage), method: :delete, data: { confirm: 'Are you sure?' } %>
			    </div>
		  	</div>
		<% end%>
		<div class="col-md-12">
			<%= f.submit "Save Order", class: "btn btn-success pull-right"%>
		</div>
	<% end %>
</div>

app/views/admin/holes/_hole_image_upload_modal.html.erb
<div id= <%= "hole-#{hole_num}-hole-image-upl-modal" %>  class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Image</h4>
      </div>
      <div class="modal-body">
      <div id="message"></div>
        <%=form_for hole, url: admin_add_hole_image_path, method: "post", :html => { :multipart => true }, :remote => true do |v|%>
            <%= file_field_tag "images[]", type: :file, multiple: true,  style: "padding: 10 0px; margin:10px 0px;" %>
            <%#= v.file_field :image , style: "padding: 10 0px; margin:10px 0px;"%>
            <%= v.hidden_field :hole_id ,value: hole.id%>
            <%= v.submit 'Upload', id: 'fileUpload', class: "btn btn-success upload-btn"%>
        <%end%>
        
        <%= render :partial => 'admin/holes/gallery', locals: {hole: hole} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_hole_images_popup.html.erb
<div id="hole-images-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Gallery</h4>
      </div>
      <div class="modal-body">
        <%= render "admin/holes/gallery", hole: @hole %>                
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_image_upload_modal.html.erb
<div id= <%= "hole-#{hole_num}-image-upl-modal" %>  class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Cover</h4>
      </div>
      <div class="modal-body">
      <div id="message"></div>
        <%=form_for hole, url: admin_add_image_path, method: "post", :html => { :multipart => true }, :remote => true do |v|%>
            <%= v.file_field :image , style: "padding: 10 0px; margin:10px 0px;"%>
            <%= v.hidden_field :hole_id ,value: hole.id%>
            <%= v.submit 'Upload', id: 'fileUpload', class: "btn btn-success upload-btn"%>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_logo_image_upload_modal.html.erb
<div id= <%= "hole-#{hole_num}-logo-image-upl-modal" %>  class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Logo</h4>
      </div>
      <div class="modal-body">
      <div id="message"></div>
        <%=form_for hole, url: admin_add_logo_image_path, method: "post", :html => { :multipart => true }, :remote => true do |v|%>
            <%= v.file_field :logo_image , style: "padding: 10 0px; margin:10px 0px;"%>
            <%= v.hidden_field :hole_id ,value: hole.id%>
            <%= v.submit 'Upload', id: 'fileUpload', class: "btn btn-success upload-btn"%>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_map_upload_modal.html.erb
<div id= <%= "hole-#{hole_num}-map-upl-modal" %>  class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Map</h4>
      </div>
      <div class="modal-body">
      <div id="message"></div>
        <%=form_for hole, url: admin_add_map_path, method: "post", :html => { :multipart => true }, :remote => true do |v|%>
            <%= v.file_field :map , style: "padding: 10 0px; margin:10px 0px;"%>
            <%= v.hidden_field :hole_id ,value: hole.id%>
            <%= v.submit 'Upload', id: 'fileUpload', class: "btn btn-success upload-btn"%>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_video_upload_modal.html.erb
<div id= <%= "hole-#{hole_num}-vid-upl-modal" %>  class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Video</h4>
      </div>
      <div class="modal-body">
      <div id="message"></div>
        <%=form_for Video.new, url: admin_video_create_path, method: "post", :html => { :multipart => true }, :remote => true do |v|%>
            <%= v.file_field :video , style: "padding: 10 0px; margin:10px 0px;"%>
            <%= v.hidden_field :hole_id ,value: hole.id%>
            <%= v.submit 'Upload', id: 'fileUpload', class: "btn btn-success upload-btn"%>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/holes/_yardages.html.erb
<div class="form-group"><%= f.text_field :par, class:"col-md-12 hole-field form-control", placeholder: "Par" %></div>
<div class="form-group"><%= f.text_field :yards, class:"col-md-12 hole-field form-control", placeholder: "Yards" %></div>
<div class="form-group"><%= f.text_field :mhcp, class:"col-md-12 hole-field form-control", placeholder: "Men HCP" %></div>
<div class="form-group"><%= f.text_field :whcp, class:"col-md-12 hole-field form-control", placeholder: "Women HCP"%></div>
<div class="form-group"><%= f.text_field :description, class:"col-md-12 hole-field form-control", placeholder: "Description"%></div>

<%= hole.hidden_field :hole_num, value: hole_num%>

app/views/admin/holes/edit.html.erb
<h1>Editing Hole</h1>

<%= render 'form', hole: @hole %>

<%= link_to 'Show', @hole %> |
<%= link_to 'Back', holes_path %>

app/views/admin/holes/get_yardages.js.erb
$('.hole_yardages').html("<%= j render partial: 'yardages_update_modal' %>");
$('#hole-yardages-update-modal').modal('show');

app/views/admin/holes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Holes</h1>

<table>
  <thead>
    <tr>
      <th>Par</th>
      <th>Yards</th>
      <th>Mhcp</th>
      <th>Whcp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holes.each do |hole| %>
      <tr>
        <td><%= hole.par %></td>
        <td><%= hole.yards %></td>
        <td><%= hole.mhcp %></td>
        <td><%= hole.whcp %></td>
        <td><%= link_to 'Show', admin_hole_path(hole) %></td>
        <td><%= link_to 'Edit', edit_admin_hole_path(hole) %></td>
        <td><%= link_to 'Delete', admin_hole_path(hole), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Hole', new_hole_path %>

app/views/admin/holes/new.html.erb
<h1>New Hole</h1>

<%= render 'form', hole: @hole %>

<%= link_to 'Back', holes_path %>

app/views/admin/holes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Par:</strong>
  <%= @hole.par %>
</p>

<p>
  <strong>Yards:</strong>
  <%= @hole.yards %>
</p>

<p>
  <strong>Mhcp:</strong>
  <%= @hole.mhcp %>
</p>

<p>
  <strong>Whcp:</strong>
  <%= @hole.whcp %>
</p>

<%= link_to 'Edit', edit_admin_hole_path(@hole) %> |
<%= link_to 'Back', admin_holes_url %>