config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
namespace :admin do
  post "search", to: "search#search", as: 'search'
  resources :holes do
    get :hole_images
    post :set_images_rank
  end
  resources :score_cards
  resources :amenities
  resources :networks
  resources :resorts do
    get :courses_list
    get :courses
    get :add_course
  end
  resources :locations
  resources :courses do
    get :holes_list
    get :get_course_images
    post :set_images_rank
  end
  resources :ads
  # resources :videos
  get "users/index"
  get "courses/holes/:id", to: 'courses#holes',as: 'holes_create'
  post "courses/remove_course_image", to: 'courses#remove_course_image'
  post "courses/remove_scorecard_image", to: 'courses#remove_scorecard_image'
  get "/add_playlist_item", to: 'courses#add_playlist_item'
  get "/add_scorecard", to: 'courses#add_scorecard'
  post "videos/create", to: 'videos#create' ,as: 'video_create'
  get "videos/:id" , to: 'videos#show' ,as: 'video'
  post "tags/:video_id/save" ,to: 'tags#create', as: 'create_tag'
  delete "tags/:id" ,to: 'tags#destroy', as: 'delete_tag'
  post "holes/add_image" ,to: 'holes#add_image', as: 'add_image'
  post "holes/add_logo_hyperlink" ,to: 'holes#add_logo_hyperlink', as: 'add_logo_hyperlink'
  post "holes/add_logo_image" ,to: 'holes#add_logo_image', as: 'add_logo_image'
  put "holes/image/:id" ,to: 'holes#remove_image', as: 'remove_image'
  put "holes/logo_image/:id" ,to: 'holes#remove_logo_image', as: 'remove_logo_image'
  post "holes/add_map" ,to: 'holes#add_map', as: 'add_map'
  put "holes/map/:id" ,to: 'holes#remove_map', as: 'remove_map'
  post "holes/add_hole_image" ,to: 'holes#add_hole_image', as: 'add_hole_image'
  delete "holes/gallery/:id" ,to: 'holes#remove_hole_image', as: 'remove_hole_image'
  post "ads/add_image" ,to: 'ads#add_image', as: 'upload_image'
  post "holes/add_yardages" ,to: 'holes#add_yardages', as: 'add_yardages'
  get "/get_yardages", to: 'holes#get_yardages', as: 'get_hole_yardages'
  delete "videos/:id" ,to: 'videos#destroy', as: 'delete_video'
  post "courses/:course_id/update_holes", to: "courses#update_holes", as: 'update_holes_details'
end

  devise_for :admins
  devise_for :users
  # put '/users', :to => 'devise/registrations#update', :as => :update_user
  namespace :v1, defaults: {format: :json} do
    delete '/sessions', :to => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :registrations, only: [:create]
    resources :pages, only: [:index]
    resources :courses, only:[:index,:show]
    resources :users, only:[:show, :update]
    resources :videos, only:[:show]
    resources :lists, only: [:create, :show]
    resources :reviews, only: [:show]
    resources :scores, only: [:create, :show]
    post "lists/:id/add_course", to: 'lists#add_course', as: 'add_course'
    post "courses/:id/add_user", to: 'courses#add_user', as: 'add_user'
    get "users/:id/lists" , to: 'users#lists', as: 'user_lists'
  end

  root to: "admin/courses#new"

  namespace :embed do
    # resources :pages, only: :show, path: "" # -> domain.com/embed/1
    get "show/:id", to: 'pages#show'
    get ":id", to: 'pages#display',as: 'display_info'
    get "dis2/:id", to: 'pages#dis2'
    get "hole/:id", to: 'pages#hole_by_hole',as: 'hole_info'
    get "course/:id", to: 'pages#course_home',as: 'course_info'
    post "pages/update_tee_scorecard", to: 'pages#update_tee_scorecard'
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/network.rb
class Network < ApplicationRecord
    has_many :courses
end

app/controllers/admin/networks_controller.rb
class Admin::NetworksController < ApplicationController
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  # GET /networks
  # GET /networks.json
  def index
    @networks = Network.all
  end

  # GET /networks/1
  # GET /networks/1.json
  def show
  end

  # GET /networks/new
  def new
    @network = Network.new
  end

  # GET /networks/1/edit
  def edit
  end

  # POST /networks
  # POST /networks.json
  def create
    @network = Network.new(network_params)

    if @network.save
     @flash_class = "alert alert-success"
     @message = "Network added successfully." 
    else
      @flash_class = "alert alert-danger"
      @message = "Something went wrong."
    end
    
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /networks/1
  # PATCH/PUT /networks/1.json
  def update
    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to admin_networks_path, notice: 'Network was successfully updated.' }
        format.json { render :show, status: :ok, location: @network }
      else
        format.html { render :edit }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  # DELETE /networks/1.json
  def destroy
    @network.destroy
    respond_to do |format|
      format.html { redirect_to admin_networks_url, notice: 'Network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:name)
    end
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/admin/networks/_form.html.erb
<div class="dynamic-fields"><%= ntw.text_field :name, class:"network-name-field form-control col-md-8 inline", placeholder: "Network Name", id:'network-name-field', style: 'width:80%; margin-left:10px;'%></div>

app/views/admin/networks/_new_modal.html.erb
<div id="new_network" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add New Network</h4>
      </div>
      <div class="modal-body">
      <div id ="network-message"></div>
        <%= form_for Network.new, :url => admin_networks_path, :method => :post, :remote => true do  %>
          <%= text_field_tag :name, nil, placeholder: 'Enter Name', class: "form-control margin-10" ,name: 'network[name]' %>
          <%= submit_tag "Save", class: "save-tag-btn btn btn-primary margin-10" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/networks/create.js.erb
$('#network-message').html(
        `<div class=  '<%=@flash_class%>' >
            <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
            <div id='flash_notice'><%=@message%></div>
        </div>`

      )

$('#network').append($('<option>', {
    value: "<%=@network.id%>",
    text: "<%=@network.name%>"
}));

app/views/admin/networks/edit.html.erb
<h1>Editing Network</h1>

<%#= render 'form', network: @network %>
<%= form_for(@network, url: {controller: 'networks', action: 'update'}, method: "put" ) do |form|%>
  <% if @network.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@network.errors.count, "error") %> prohibited this network from being saved:</h2>

      <ul>
      <% @network.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :network_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%#= link_to 'Show', @network %> |
<%= link_to 'Back', admin_networks_path %>

app/views/admin/networks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Networks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @networks.each do |network| %>
      <tr>
        <td><%= network.name %></td>
        <td><%#= link_to 'Show', admin_network_path(network) %></td>
        <td><%= link_to 'Edit', edit_admin_network_path(network) %></td>
        <td><%= link_to 'Delete', admin_network_path(network), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Network', new_admin_network_path %>
<style type="text/css">
td {
  padding: 10px;
}
</style>

app/views/admin/networks/new.html.erb
<h1>New Network</h1>

<%= render 'form', network: @network %>

<%= link_to 'Back', networks_path %>

app/views/admin/networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @network.name %>
</p>

<%= link_to 'Edit', edit_network_path(@network) %> |
<%= link_to 'Back', networks_path %>