config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
namespace :admin do
  post "search", to: "search#search", as: 'search'
  resources :holes do
    get :hole_images
    post :set_images_rank
  end
  resources :score_cards
  resources :amenities
  resources :networks
  resources :resorts do
    get :courses_list
    get :courses
    get :add_course
  end
  resources :locations
  resources :courses do
    get :holes_list
    get :get_course_images
    post :set_images_rank
  end
  resources :ads
  # resources :videos
  get "users/index"
  get "courses/holes/:id", to: 'courses#holes',as: 'holes_create'
  post "courses/remove_course_image", to: 'courses#remove_course_image'
  post "courses/remove_scorecard_image", to: 'courses#remove_scorecard_image'
  get "/add_playlist_item", to: 'courses#add_playlist_item'
  get "/add_scorecard", to: 'courses#add_scorecard'
  post "videos/create", to: 'videos#create' ,as: 'video_create'
  get "videos/:id" , to: 'videos#show' ,as: 'video'
  post "tags/:video_id/save" ,to: 'tags#create', as: 'create_tag'
  delete "tags/:id" ,to: 'tags#destroy', as: 'delete_tag'
  post "holes/add_image" ,to: 'holes#add_image', as: 'add_image'
  post "holes/add_logo_hyperlink" ,to: 'holes#add_logo_hyperlink', as: 'add_logo_hyperlink'
  post "holes/add_logo_image" ,to: 'holes#add_logo_image', as: 'add_logo_image'
  put "holes/image/:id" ,to: 'holes#remove_image', as: 'remove_image'
  put "holes/logo_image/:id" ,to: 'holes#remove_logo_image', as: 'remove_logo_image'
  post "holes/add_map" ,to: 'holes#add_map', as: 'add_map'
  put "holes/map/:id" ,to: 'holes#remove_map', as: 'remove_map'
  post "holes/add_hole_image" ,to: 'holes#add_hole_image', as: 'add_hole_image'
  delete "holes/gallery/:id" ,to: 'holes#remove_hole_image', as: 'remove_hole_image'
  post "ads/add_image" ,to: 'ads#add_image', as: 'upload_image'
  post "holes/add_yardages" ,to: 'holes#add_yardages', as: 'add_yardages'
  get "/get_yardages", to: 'holes#get_yardages', as: 'get_hole_yardages'
  delete "videos/:id" ,to: 'videos#destroy', as: 'delete_video'
  post "courses/:course_id/update_holes", to: "courses#update_holes", as: 'update_holes_details'
end

  devise_for :admins
  devise_for :users
  # put '/users', :to => 'devise/registrations#update', :as => :update_user
  namespace :v1, defaults: {format: :json} do
    delete '/sessions', :to => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :registrations, only: [:create]
    resources :pages, only: [:index]
    resources :courses, only:[:index,:show]
    resources :users, only:[:show, :update]
    resources :videos, only:[:show]
    resources :lists, only: [:create, :show]
    resources :reviews, only: [:show]
    resources :scores, only: [:create, :show]
    post "lists/:id/add_course", to: 'lists#add_course', as: 'add_course'
    post "courses/:id/add_user", to: 'courses#add_user', as: 'add_user'
    get "users/:id/lists" , to: 'users#lists', as: 'user_lists'
  end

  root to: "admin/courses#new"

  namespace :embed do
    # resources :pages, only: :show, path: "" # -> domain.com/embed/1
    get "show/:id", to: 'pages#show'
    get ":id", to: 'pages#display',as: 'display_info'
    get "dis2/:id", to: 'pages#dis2'
    get "hole/:id", to: 'pages#hole_by_hole',as: 'hole_info'
    get "course/:id", to: 'pages#course_home',as: 'course_info'
    post "pages/update_tee_scorecard", to: 'pages#update_tee_scorecard'
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/embed/pages_controller.rb
class Embed::PagesController < ApplicationController
  before_action :set_course, only: [:show]
  # after_filter :allow_iframe, only: [:show, :awesome_embed]
  after_action :set_version_header
  # layout "embed", only: [:show]
  layout "embed"
  layout "display", only: [:display]

  def show
    gon.hole_num = []
    gon.videos = []
    gon.videos_urls = []
    gon.tags = []
    gon.par = []
    gon.yard = []
    gon.mhcp = []
    gon.image = []
    gon.image_urls = []
    gon.description = []

    @job = "547"
    @course = Course.find(params[:id])
    @xh = @course.holes
    @holes = @course.holes.sort_by{ |m| m.hole_num }
    @holes.each do |hole|
      gon.hole_num << hole.hole_num if hole.video.present?
      gon.videos << hole.video  if hole.video.present?
      gon.videos_urls << hole.video.video if hole.video.present?
      gon.tags << hole.video.tags  if hole.video.present?
      gon.par << hole.par if hole.video.present?
      gon.yard << hole.yards if hole.video.present?
      gon.mhcp << hole.mhcp if hole.video.present?
      gon.image << hole.image_file_name if hole.video.present?
      gon.image_urls << hole.image.url if hole.video.present?
      gon.description << hole.description if hole.video.present?
    end
    @videos_urls = gon.videos_urls
  end

  def display
    gon.videos_urls = []
    gon.image_urls = []
    @teename = []
    @course = Course.find(params[:id])
    @course_status = @course.resort.hide_carousel
    @resort = @course.resort
    resolution = (is_mobile? ? 'mobile' : 'medium').to_sym
    @course.playlist_items.each do |video|
      gon.videos_urls << video.video.url(resolution).gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net').gsub("http", "https") if video.video.present?
      gon.image_urls << video.thumbnail_image.url.gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net').gsub("http", "https") if video.thumbnail_image.present?
    end
    @videos_urls = gon.videos_urls
    @holes = @course.holes.order("hole_num")
    @score_cards = @course.sorted_scorecards
    @course.score_cards.each do |scorecard|
      @teename << [scorecard.tee_name, scorecard.id, scorecard.color]
    end
    
  end

  def hole_by_hole
    @hide_carousal = true 
    gon.hole_num = []
    gon.videos = []
    gon.videos_urls = []
    gon.tags = []
    gon.par = []
    gon.yard = []
    gon.mhcp = []
    gon.image = []
    gon.image_urls = []
    gon.description = []
    @hole = Hole.find(params[:id])
    @course = Course.find(@hole.course_id)
    @course_color = Course.find(@hole.course_id).color_selector
    @holes = @course.holes.sort_by{ |m| m.hole_num }
    resolution = (is_mobile? ? 'mobile' : 'medium').to_sym
    @holes.each do |hole|
      gon.hole_num << hole.hole_num if hole.video.present?
      gon.videos << hole.video  if hole.video.present?
      gon.videos_urls << hole.video.video.url(resolution).gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net') if hole.video.present?
      gon.tags << hole.video.tags  if hole.video.present?
      gon.par << hole.par if hole.video.present?
      gon.yard << hole.yards if hole.video.present?
      gon.mhcp << hole.mhcp if hole.video.present?
      gon.image << hole.image_file_name if hole.video.present?
      gon.image_urls << hole.image.url.gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net') if hole.video.present?
    end
    @videos_urls = gon.videos_urls
  end

  def course_home
    
    @hide_carousal = true 
    gon.videos_urls = []
    gon.image_urls = []
    @teename = []
    @course = Course.find(params[:id])
    
    resolution = (is_mobile? ? 'mobile' : 'medium').to_sym
    @course.playlist_items.each do |video|
      gon.videos_urls << video.video.url(resolution).gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net') if video.video.present?
      gon.image_urls << video.thumbnail_image.url.gsub('s3-us-west-2.amazonaws.com/fore92', 'd1s5na5d5z3eyp.cloudfront.net') if video.thumbnail_image.present?
    end
    @videos_urls = gon.videos_urls
    @holes = @course.holes.order("hole_num")
    @score_cards = @course.sorted_scorecards
    @course.score_cards.each do |scorecard|
      @teename << [scorecard.tee_name, scorecard.id, scorecard.color]
    end
  end

  def update_tee_scorecard
    @scorecard = ScoreCard.find(params[:sid])
  end

  def awesome_embed
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def set_version_header
      # response.set_header("X-Frame-Options", "ALLOWALL")
      response.headers.except! 'X-Frame-Options'
    end
end

app/controllers/embed/pages_controller_old.rb
class Embed::PagesController < ApplicationController
  before_action :set_course, only: [:show]
  after_action :set_version_header

  def show
    gon.videos = []
    gon.videos_urls = []
    gon.tags = []
    @course.holes.each do |hole|
      gon.videos << hole.video if hole.video.present?
      gon.videos_urls << hole.video.video if hole.video.present?
      gon.tags << hole.video.tags if hole.video.present?
    end
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def set_version_header
        # response.headers['X-Frame-Options'] = 'AllowAll'
        response.set_header("X-Frame-Options", "AllowAll")

    end
end

app/views/embed/pages/_course_home_video_container.html.erb
<%= Gon::Base.render_data %>
<div class= "player-container" progress-color="<%=color_selector(@course.color_selector)%>">

  <% if @videos_urls.size > 1 %>
    <div class="slider-bg-color slider-bg-prev"><div class="previous on-video"> <%= image_tag "left.png" %> </div> </div>
    <div class="slider-bg-color-right slider-bg-right"><div class="next on-video"><%= image_tag "right.png" %></div> </div>
  <% end %>
  <div  class = "upper-gradient">
    <% if @course.logo_hyperlink %>
    
     <div class="logo on-video"><%= link_to image_tag(logo_on_video(@course)), @course.logo_hyperlink, target: :_blank %></div>
    <% else%>
      <div class="logo on-video"><%= link_to image_tag(logo_on_video(@course)), admin_resort_courses_list_path(@course.resort), target: :_blank %></div>
<% end %>
  </div>
  <% sibling_courses = @course.sibling_courses %>
  <div  class = "lower-gradient"></div>
  <div class="vplayer" id="vplayer">

    <video id="home-vid" class="video-js vjs-default-skin vjs-big-play-centered video_container" playsinline></video>

  </div>

    <div class="merge-dropdown-home">
      <% if sibling_courses.count > 0 %>
        <div class="dropdown">
          <ul class="dropdown-menu on-home">
            <li>
              <a style="color: #0083A9;" href="JavaScript:void(0);">
                Select Course:
              </a>
            </li>
            <% @course.resort.courses.each do |course| %>
              <li>
                <%= link_to embed_display_info_path(course), data: { turbolinks: false} do %>
                  <%= course.name %>
                  <% if @course.id == course.id %>
                  <label style="width:100px;height:10px;color:red;"> sample </label>
                    <i class="fa fa-check" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="vjs-playlist">

        <div id="0" class="hole-home active">
          <%= link_to "javascript:void(0);" do %>
            <%= image_tag('hole-home.png') %>
          <% end %>
        </div>
        <div class="left-green">
          <svg version="1.1" id="Layer_1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" x="0px" y="0px"
           width="19px" viewBox="0 0 15.225 26.936" enable-background="new 0 0 15.225 26.936" xml:space="preserve" style="margin-top:9px;">
            <path fill-rule="evenodd" clip-rule="evenodd" fill="<%=color_selector(@course.color_selector)%>" d="M12.664,0.439c0.586-0.586,1.535-0.586,2.121,0
            c0.585,0.585,0.585,1.535,0,2.121L3.62,13.725l10.651,10.65c0.586,0.586,0.586,1.536,0,2.121c-0.586,0.586-1.535,0.586-2.121,0
            L0.439,14.785c-0.586-0.586-0.586-1.535,0-2.121L12.664,0.439z"/>
          </svg>
        </div>
        <div  class="playlist">
          <ul id="playlist" >
            <% @holes.try(:each) do |hole| %>
              <li id="<%=hole.hole_num%>" class= "hole-number" hole_image= "<%= hole.logo_image.present? ? hole.logo_image.url : logo_on_video(@course)%>" logo_hyperlink = "<%= hole.logo_hyperlink.present? ? hole.logo_hyperlink : hyperlink_on_video(@course)%>" color="<%=color_selector(@course.color_selector)%>">
                <%=link_to embed_hole_info_path(hole.id, hole_num: hole.hole_num), remote: true do %>
                  <span><%= hole.hole_num %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="right-green">
          <svg version="1.1" id="Layer_1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" x="0px" y="0px"
           width="19px" viewBox="0 0 15.225 26.936" enable-background="new 0 0 15.225 26.936" xml:space="preserve" style="margin-top:9px;">
            <path fill-rule="evenodd" clip-rule="evenodd" fill="<%=color_selector(@course.color_selector)%>" d="M2.561,0.439c-0.586-0.586-1.535-0.586-2.121,0
            c-0.585,0.585-0.585,1.535,0,2.121l11.165,11.164L0.953,24.375c-0.586,0.586-0.586,1.536,0,2.121c0.586,0.586,1.535,0.586,2.121,0
            l11.711-11.711c0.586-0.586,0.586-1.535,0-2.121L2.561,0.439z"/>
          </svg>
        </div>
      </div>
    </div>
</div>
<style type="text/css">
.fa-check:before {
  color: #0083A9;
  padding-left: 8px;
  font-size: 18px;
}
.merge-dropdown-home{
  position: relative;
  z-index: 200;
}
.on-home{
  display: none;
  top: auto !important;
  left: 0px;
  position: absolute;
  max-width: 100%;
  color: white;
  bottom: 0px !important;
}
.on-home li{
  padding: 5px 0px !important;
}
.playlist ul li{
  display: table-cell !important;
}

.scorecard-tee h3{
  padding: 5px 0px;
  width:auto;
}

.scorecard-drop h4{
 width:auto;
 padding-left: 7px;
}

.tee_button_scr h4{
  width:auto;
  padding: 1% 15px 1% 15px;
}

@media only screen and (max-width: 479px) {

}
</style>
<script type="text/javascript">
  $(document).ready(function() {
    if(<%= @course.resort.hide_carousel == true%>){
      $(".merge-dropdown-home").addClass("hidden");
    }
  });
  $(function(){
    function handlerIn() {
      $(".merge-dropdown-home").find(".dropdown-menu").show();
    }
    function handlerOut() {
      $(".merge-dropdown-home").find(".dropdown-menu").hide();
    }
    $("#0").hover(handlerIn, handlerOut);
    $(".on-home").hover(handlerIn, handlerOut);
    $("#0").click(function(){
      $(".merge-dropdown-home").find(".dropdown-menu").toggle();
    })

    $(".hole-home").on("click", function(e) {
      $.ajax({
        url: '<%= embed_course_info_path(@course.id) %>',
        type: 'GET',
        dataType: "script"
      })
    });
    var videoList = []
    for (var i = 0, len = gon.videos_urls.length; i < len; i++) {
      videoList.push({
        sources: [{
          src: gon.videos_urls[i],
          type: 'video/mp4'
        }],
        poster: gon.image_urls[i]
      });
    }
    var player = videojs('home-vid', {
      controls: true, fluid:true,
      'playbackRates': [0.5, 1, 1.5, 2],
      abr: {enable: true},
      controlBar: {
        children: {
          'playToggle':{},
          'progressControl':{},
          'volumeMenuButton':{},
          'volumePanel': {inline: false},
          'playbackRateMenuButton':{},
          'fullscreenToggle':{}
        }
      }
    });


    try {player.volume(1);} catch (e) {}
    player.playlist(videoList);
    player.playlist.autoadvance(0);

    player.on('play', function(){
      var current_src = player.currentSrc();
      if(!current_src.includes("https")){
        current_src = current_src.replace("http","https")
      }
      var playing_item = $("ul.playlist_thumb").find("[data-current-src='" + current_src + "']");
      $("li.playing").removeClass('playing');
      playing_item.addClass('playing');
    });


    $('.playlist_items').on('click', function(){
      var clicked_item = $(this).attr('data-video-index');
      var player = videojs('home-vid');
      player.playlist.currentItem(parseInt(clicked_item));
      player.play();
    });


    player.on('ended', function(){
      $("li.playing").removeClass('playing');
      if(player.playlist.lastIndex() == player.playlist.currentIndex()){
        <% if @course_status == false %>
           localStorage.setItem("hole_auto_play", true);
           $(".hole-number#1 a").click()
        <%else%>
           //alert(videoList.length)
           //player.playlist(videoList);
             player.playlist(videoList);
             player.play();
        <%end%>
        
      }
    });

    
    $(".hole-number").click(function(){
      logoImage = $(this).attr('hole_image');
      logoHyperlink = $(this).attr('logo_hyperlink');
    })

    $(document).ready(function() {
      bgcolor = $('.player-container').attr('progress-color');
      progressColor(bgcolor);
    });


    $('.player-container').hover(
      function(event){
        bgcolor = $(this).attr('progress-color');
        showBars();
        progressColor(bgcolor);
      }, function(){
        if (!player.paused()){
          hideBars();
        }
      }
    );

    var timer;

    $firstElement = 0;
    player.on("loadedmetadata",function () {
      if($(window).width() < 760 && player.paused()){
        showPlayerActions();
      }else{
        showBars();
      }
      timer = setTimeout(function(){hideBars()}, 5000);
      $('.vjs-volume-panel').removeClass('vjs-hidden');
      $('.vjs-mute-control').removeClass('vjs-hidden');
      $('.vjs-volume-control').removeClass('vjs-hidden');
    });

    player.on("userinactive",function () {
      if (!player.paused()){
        hideBars();
      }
    });

    player.on("useractive",function () {
        showBars();
        clearTimeout(timer);
    });

    <% if @videos_urls.size > 1 %>
    $(function(){
      // document.querySelector('.previous').addEventListener('click', function() {
      //   player.playlist.previous();
      // });
      // document.querySelector('.next').addEventListener('click', function() {
      //   player.playlist.next();
      // });

      document.querySelector('.slider-bg-prev').addEventListener('click', function() {
        player.playlist.previous();
      });

      document.querySelector('.slider-bg-right').addEventListener('click', function() {
        player.playlist.next();
      });

    });
   <% end %>


    var nextActiveId;
    $firstElement = 0;

    document.querySelector('.right-green').addEventListener('click', function() {
      if($(window).width() < 350){
        nextActiveId = $firstElement + 1;
      }
      else if($(window).width() >= 350 && $(window).width() < 480){
        nextActiveId = $firstElement + 2;
      }
      else if($(window).width() >= 480 && $(window).width() < 600){
        nextActiveId = $firstElement + 3;
      }
      else if($(window).width() >= 600 && $(window).width() < 760){
        nextActiveId = $firstElement + 5;
      }
      else if($(window).width() >= 760 && $(window).width() < 960){
        nextActiveId = $firstElement + 6;
      }
      else if($(window).width() >= 960 && $(window).width() < 1200){
        nextActiveId = $firstElement + 9;
      }
      else if($(window).width() >= 1200){
        nextActiveId = $firstElement + 10;
      }
      if(nextActiveId == 0 || $("#playlist").find("#"+nextActiveId).size() != 0){
        scrollTo(nextActiveId);
        $firstElement = nextActiveId
      }
    });

    document.querySelector('.left-green').addEventListener('click', function() {
      if($(window).width() < 350){
        nextActiveId = $firstElement - 1;
      }
      else if($(window).width() >= 350 && $(window).width() < 480){
        nextActiveId = $firstElement - 2;
      }
      else if($(window).width() >= 480 && $(window).width() < 600){
        nextActiveId = $firstElement - 3;
      }
      else if($(window).width() >= 600 && $(window).width() < 760){
        nextActiveId = $firstElement - 5;
      }
      else if($(window).width() >= 760 && $(window).width() < 960){
        nextActiveId = $firstElement - 6;
      }
      else if($(window).width() >= 960 && $(window).width() < 1200){
        nextActiveId = $firstElement - 9;
      }
      else if($(window).width() >= 1200){
        nextActiveId = $firstElement - 10;
      }
      if (nextActiveId < 0){
        nextActiveId = 0
      }
      if(nextActiveId == 0 || $("#playlist").find("#"+nextActiveId).size() != 0){
        scrollTo(nextActiveId);
        $firstElement = nextActiveId
      }
    });

    function scrollTo(a){
      // currPos = $(".playlist").scrollLeft();
      liWidth = $(".playlist ul li").outerWidth(true);
      scrollValue = a*liWidth;
      $('.playlist').animate( { scrollLeft: scrollValue }, 500);

    }

    if(mobilecheck()){
      $('button.vjs-playback-rate').on('click touchstart',function(){
        $('.vjs-menu').css({"display":"block"})
        $('.vjs-menu').removeClass('hide')
      });
      $('.vjs-menu-item').on('click touchstart',function(){
        $('.vjs-menu').addClass('hide')
      });
    }
  })
// });
</script>

app/views/embed/pages/_course_specs.html.erb
<%#if params["action"] == "course_home"%>
	<!-- <li><span><b><%#=@course.total_par%></b></span><p>PAR</p></li>
	<li><span><b><%#=@course.length%></b></span><p>YARDS</p></li>
	<li><span><b><%#=@course.rating%></b></span><p>RATING</p></li>
	<li class="slop-right-border"><span><b><%#=@course.slope%></b></span><p>SLOPE</p></li> -->
<%#else%>
	<!-- <li><span><b><%#=@total_par%></b></span><p>PAR</p></li>
	<li><span><b><%#=@total_yards%></b></span><p>YARDS</p></li>
	<li><span><b><%#=@tee_rating%></b></span><p>RATING</p></li>
	<li class="slop-right-border"><span><b><%#=@tee_slope%></b></span><p>SLOPE</p></li> -->
<%#end%>
<%if score_card%>
  <li><span><b><%=score_card.total_par %></b></span><p>PAR</p></li>
  <li><span><b><%=score_card.total_yards %></b></span><p>YARDS</p></li>
  <li><span><b><%=score_card.rating %></b></span><p>RATING</p></li>
  <li class="slop-right-border"><span><b><%=score_card.slope %></b></span><p>SLOPE</p></li>
<%end%>

app/views/embed/pages/_scorecard_updated_data.html.erb
<div class="topborder" style="margin-right: 0px;">
  <div class="mobile-scroll">
    <table class="score-specs">
      <tbody>
        <tr class="rowcolumns" color="<%=color_selector(score_card.course.color_selector)%>">
          <td class="rowstart">TEE</td>
          <% 18.times do |t| %>
           <%t+=1%>
           <td class="rowcolumns"><%=t%></td>
           <%if t == 9 %>
            <td class="rowstart">OUT</td>
           <% end %>
          <% end %>
          <td class="rowstart">IN</td>
          <td class="rowstart">TOT</td>
        </tr>
        <tr class="updated-rows">
          <td class="rowstart">YDS</td>
          <% yards_data = score_card.get_yards_data %>
          <% yards_data.each do |yard| %>
            <td class="rowcolumns"><%= yard %></td>
          <% end %>
        </tr>
        <tr class="updated-rows">
          <td class="rowstart">PAR</td>
          <% pars_data = score_card.get_pars_data %>
          <% pars_data.each do |par| %>
            <td class="rowcolumns"><%= par %></td>
          <% end %>
        <tr class="updated-rows">
          <td class="rowstart">HCP</td>
          <% hcps_data = score_card.get_hcps_data %>
          <% hcps_data.each do |hcp| %>
            <td class="rowcolumns"><%= hcp %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/embed/pages/course_home.js.erb
$('.hole-info-div').html('<%= j render("course_information") %>');
if ($('#home-vid').length == 0){
  var player = videojs('hole-vid');
  player.dispose();
  $(".player-container").remove();
  $(".main-container").prepend("<%= j render partial: 'course_home_video_container' %>");
}
$("li.active").removeClass('active');
$(".hole-home").addClass('active');

app/views/embed/pages/dis2.html.erb
<div class="fore-test-iframe">
  <iframe src="http://ec2-34-209-118-108.us-west-2.compute.amazonaws.com/embed/33" width="100%"  allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="height:100vh; border: none;" id="fore_videos_iframe" onload="resizeIframe(this)"> </iframe>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="https://d1s5na5d5z3eyp.cloudfront.net/assets/iframeResizer.min.js"></script>
<script type="text/javascript">iFrameResize({log: true, enablePublicMethods: true });</script>
<script type="text/javascript">
  $(window).bind("pageshow", function(event) {
    if (event.originalEvent.persisted) {
      window.location.reload();
    }
    var iframe = $(document).find('div.fore-test-iframe iframe');
    iframe.src = iframe.attr('src');
  });
  if ($('.player-container .vplayer').children('video').length > 0){
    window.location.reload();
  }
</script>

app/views/embed/pages/hole_by_hole.html.erb
<%#= @job %>
<%= render :partial => 'hole_information' %>

app/views/embed/pages/show.html.erb
 <div> job <br> <%= @job %> </div> <br>
 <div> course <br> <%= @course %> </div> <br>

 <div> xh <br> <%= @xh %> </div> <br>
 <div> xh all <br> <%= @xh %> </div> <br>
 <div> holes <br> <%= @holes %> </div> <br>



<%= @holes %>

app/views/embed/pages/update_tee_scorecard.js.erb
$(".scorecard").html("<%= j render :partial => 'course_specs', locals: {score_card: @scorecard} %>");
$("#scorecard_updated").html("<%= j render :partial => 'scorecard_updated_data', locals: {score_card: @scorecard} %>");