config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'
namespace :admin do
  post "search", to: "search#search", as: 'search'
  resources :holes do
    get :hole_images
    post :set_images_rank
  end
  resources :score_cards
  resources :amenities
  resources :networks
  resources :resorts do
    get :courses_list
    get :courses
    get :add_course
  end
  resources :locations
  resources :courses do
    get :holes_list
    get :get_course_images
    post :set_images_rank
  end
  resources :ads
  # resources :videos
  get "users/index"
  get "courses/holes/:id", to: 'courses#holes',as: 'holes_create'
  post "courses/remove_course_image", to: 'courses#remove_course_image'
  post "courses/remove_scorecard_image", to: 'courses#remove_scorecard_image'
  get "/add_playlist_item", to: 'courses#add_playlist_item'
  get "/add_scorecard", to: 'courses#add_scorecard'
  post "videos/create", to: 'videos#create' ,as: 'video_create'
  get "videos/:id" , to: 'videos#show' ,as: 'video'
  post "tags/:video_id/save" ,to: 'tags#create', as: 'create_tag'
  delete "tags/:id" ,to: 'tags#destroy', as: 'delete_tag'
  post "holes/add_image" ,to: 'holes#add_image', as: 'add_image'
  post "holes/add_logo_hyperlink" ,to: 'holes#add_logo_hyperlink', as: 'add_logo_hyperlink'
  post "holes/add_logo_image" ,to: 'holes#add_logo_image', as: 'add_logo_image'
  put "holes/image/:id" ,to: 'holes#remove_image', as: 'remove_image'
  put "holes/logo_image/:id" ,to: 'holes#remove_logo_image', as: 'remove_logo_image'
  post "holes/add_map" ,to: 'holes#add_map', as: 'add_map'
  put "holes/map/:id" ,to: 'holes#remove_map', as: 'remove_map'
  post "holes/add_hole_image" ,to: 'holes#add_hole_image', as: 'add_hole_image'
  delete "holes/gallery/:id" ,to: 'holes#remove_hole_image', as: 'remove_hole_image'
  post "ads/add_image" ,to: 'ads#add_image', as: 'upload_image'
  post "holes/add_yardages" ,to: 'holes#add_yardages', as: 'add_yardages'
  get "/get_yardages", to: 'holes#get_yardages', as: 'get_hole_yardages'
  delete "videos/:id" ,to: 'videos#destroy', as: 'delete_video'
  post "courses/:course_id/update_holes", to: "courses#update_holes", as: 'update_holes_details'
end

  devise_for :admins
  devise_for :users
  # put '/users', :to => 'devise/registrations#update', :as => :update_user
  namespace :v1, defaults: {format: :json} do
    delete '/sessions', :to => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :registrations, only: [:create]
    resources :pages, only: [:index]
    resources :courses, only:[:index,:show]
    resources :users, only:[:show, :update]
    resources :videos, only:[:show]
    resources :lists, only: [:create, :show]
    resources :reviews, only: [:show]
    resources :scores, only: [:create, :show]
    post "lists/:id/add_course", to: 'lists#add_course', as: 'add_course'
    post "courses/:id/add_user", to: 'courses#add_user', as: 'add_user'
    get "users/:id/lists" , to: 'users#lists', as: 'user_lists'
  end

  root to: "admin/courses#new"

  namespace :embed do
    # resources :pages, only: :show, path: "" # -> domain.com/embed/1
    get "show/:id", to: 'pages#show'
    get ":id", to: 'pages#display',as: 'display_info'
    get "dis2/:id", to: 'pages#dis2'
    get "hole/:id", to: 'pages#hole_by_hole',as: 'hole_info'
    get "course/:id", to: 'pages#course_home',as: 'course_info'
    post "pages/update_tee_scorecard", to: 'pages#update_tee_scorecard'
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/resort.rb
class Resort < ApplicationRecord

	include PgSearch
	pg_search_scope :search_by_name, :against => [:name]
	
    has_many :courses, :dependent => :destroy
    has_one :location, :dependent => :destroy

    accepts_nested_attributes_for :location, :allow_destroy => true
    accepts_nested_attributes_for :courses

    has_attached_file :logo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
    }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

    def formated_location
      formated_location_result = ""
      town = self.location.try(:town)
      state = self.location.try(:state)
      lat = self.location.try(:lat)
      lng = self.location.try(:lng)

      formated_location_result << town  if town
      formated_location_result << ", " + state if state

      formated_location_result
    end
end

app/controllers/admin/resorts_controller.rb
class Admin::ResortsController < ApplicationController
  #layout "display", only: [:display]
  layout "embed", only: :courses_list
  before_action :set_resort, only: [:show, :edit, :update, :destroy]
  after_action :set_version_header, only: :courses_list

  # GET /resorts
  # GET /resorts.json
  def index
    @resorts = Resort.all
  end

  # GET /resorts/1
  # GET /resorts/1.json
  def show
  end

  # GET /resorts/new
  def new
    @resort = Resort.new
  end

  # GET /resorts/1/edit
  def edit
  end

  # POST /resorts
  # POST /resorts.json
  def create
    @resort = Resort.new(resort_params)

    if @resort.save
      @flash_class = "alert alert-success"
      @message = "Resort added successfully."
    else
      @flash_class = "alert alert-danger"
      @message = "Something went wrong."
    end

    respond_to do |format|
      format.js
    end

  end

  # PATCH/PUT /resorts/1
  # PATCH/PUT /resorts/1.json
  def update
    respond_to do |format|
      if @resort.update(resort_params)
        format.html { redirect_to admin_resorts_path, notice: 'Resort was successfully updated.' }
        format.json { render :show, status: :ok, location: @resort }
      else
        format.html { render :edit }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resorts/1
  # DELETE /resorts/1.json
  def destroy
    @resort.destroy
    respond_to do |format|
      format.html { redirect_to admin_resorts_url, notice: 'Resort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def courses_list
    @resort = Resort.find(params[:resort_id])
    @courses = @resort.courses
  end

  def courses
    @resort = Resort.find(params[:resort_id])
    @courses = @resort.courses
  end

  def add_course
    @resort = Resort.find(params[:resort_id])
    @resort.courses.build
    render 'admin/courses/new'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resort
      @resort = Resort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resort_params
      params.require(:resort).permit(:name, :hide_logo, :hide_about_course, :lead_generation, :logo, :lead_url, :hide_carousel, :hide_score_card, :fore_btn_background, :fore_btn_text, :fore_line_color)
    end

    def set_version_header
      # response.set_header("X-Frame-Options", "ALLOWALL")
      response.headers.except! 'X-Frame-Options'
    end
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/admin/resorts/_form.html.erb
<div class= "dynamic-fields"><%= res.text_field :name, class:"col-md-12 resort-name-field form-control inline", placeholder: "Resort Name" , id:'resort-name-field' , style: 'width:80%;  margin-left:10px;'%></div>

app/views/admin/resorts/_new_modal.html.erb
<div id="new_resort" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add New Resort</h4>
      </div>
      <div class="modal-body">
      <div id ="resort-message"></div>
          <%= form_for Resort.new, :url => admin_resorts_path, :method => :post, :remote => true do  %>
            <%= text_field_tag :name, nil, placeholder: 'Enter Name', class: "form-control margin-10" ,name: 'resort[name]' %>
            <%= submit_tag "Save", class: "save-tag-btn btn btn-primary margin-10" %>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/resorts/courses.html.erb
<!-- Pre load vjs files for next page -->
<link href="//vjs.zencdn.net/6.2.8/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/6.2.8/video.min.js"> </script>
<script src="https://rawgit.com/atlance01/vrapp-ionic/master/www/js/lib/videojs-playlist.js"></script>


<div class="container">

<% content_for :side_nav do %>
  <%= render :partial => 'admin/shared/side_nav' %>
<% end %>

  <div class="panel panel-default">
    <h2>Course List</h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <div id="course-search-form">
          <div class="col-md-3" style="padding:0px;">
            <%= form_for('', :url => url_for(:controller => 'search', :action => 'search') , method: "post", remote: true ) do |f|%>
              <%= text_field_tag :course, "", class: "form-control", placeholder: "Search Courses",name: 'search[q]' %>
              <%= hidden_field_tag :klass, "course", class: "form-control",name: 'search[klass]' %>
              <%= hidden_field_tag :id, "courses-tbl", class: "form-control",name: 'search[id]' %>
            <% end %>
          </div>
          <div class="col-md-9">
            <%= link_to admin_resort_add_course_path(@resort), class: "btn btn-info btn-add pull-right", title: "Add another course" do %>
              +
            <% end %>
          </div>
        </div>
        <table class="table table-striped" id="courses-tbl">
          <thead>
            <tr>
              <th>Cover</th>
              <th>Name</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @courses.each do |course| %>
              <tr>
                <td><%= image_tag (course.cover.url), style: "width: 50px;" %></td>
                <td><%= link_to course.name, admin_course_path(course) %></td>
                <td><%= link_to 'Edit', edit_admin_course_path(course) %> | <%= link_to 'Delete', admin_course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>


</div>

app/views/admin/resorts/courses_list.html.erb
<style>
  .se-pre-con {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background-image: url(<%= asset_url('preloader.gif') %>);
    background-repeat: no-repeat;
    background-position: center;
    background-color: #fff;
  }
</style>
<div class="se-pre-con"></div>
<script>
  $(window).load(function() {
    $(".se-pre-con").fadeOut('slow');
  });
</script>
<div class="clearfix"></div>
<div class="select_course_body clearfix">
	<% @courses.each do |course| %>
		<%= link_to embed_display_info_path(course), class: "play_button", data: { turbolinks: false} do %>
			<%= image_tag "big-play.png" %>
			<div class="col-md-12 course_list_item">
				<%= image_tag course.cover.url.gsub("http", "https") %>
				<div class="course_info">
					<h2 class="course_title"><%= course.name %></h2>
					<p class="course_description" title="<%= course.bio %>"><%= course.bio %></p>
				</div>
			</div>
		<% end %>
	<% end %>
</div>
<div class="signature pb-20 select_course_footer">
  <div class='col-md-12 col-sm-12'>
    <div class='col-md-4 col-sm-6 col-xs-6 col-md-offset-8 col-sm-offset-6 col-xs-offset-6 p0'>
      <% unless @resort.hide_logo %>
        <%= link_to image_tag("signature_v3.png"), "https://foregolf.com", target: :_blank %>
      <% end %>
    </div>
  </div>
</div>
<style type="text/css">
	.play_button{
		position: relative;
		display: block;
		width: 100%;
		float: left;
	}
	.play_button > img{
		position: absolute;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	  z-index: 9;
	  max-width: 70px;
	}

	.select_course_body a:hover{
		background-color: white;
	}
</style>
<script>
$(document).ready(function(){
  $(".se-pre-con").fadeOut('slow');
})
</script>

app/views/admin/resorts/create.js.erb
$('#resort-message').html(
        `<div class=  '<%=@flash_class%>' >
            <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
            <div id='flash_notice'><%=@message%></div>
        </div>`

      )

$('#resort').append($('<option>', {
    value: "<%=@resort.id%>",
    text: "<%=@resort.name%>"
}));

app/views/admin/resorts/edit.html.erb
<div id="course-page-content-wrapper" class="col-md-12" style="margin-top: 0px;">
  <%= form_for(@resort, url: {controller: 'resorts', action: 'update'}, method: "put" ) do |f|%>
    <div class="col-md-12 course-info-row">
      <div class="col-md-12">
        <h4>Client Information</h4>
      </div>
      <div class="basic-course-info">
        <div class="col-md-12 course-info-row">
          <div class="col-md-4 form-group">
            <%= label_tag :name ,'Name',class:"col-md-12 zero-left-right-padd"%>
            <%= f.text_field :name , class:"col-md-12 form-control check-field", placeholder: "Full name of Client"%>
          </div>
          <div class="col-md-8 form-group">
            <%= f.fields_for :location do |location_form| %>
              <%= render 'admin/locations/form.html.erb', location_form: location_form %>
            <% end %>
          </div>
        </div>
        <div class="col-md-12 course-info-row">
          <div class="col-md-4">
            <%= label_tag :course_type ,'Client Type',class: "col-md-12 zero-left-right-padd" %>
            <%= check_box_tag 'resort[resort_type]' ,'is_public', @resort.resort_type == "is_public", class: 'checkbox check-field inline', id: 'course_type_public' %>
            <span class="inline">Public</span>
            <div class="inline">
              <%= check_box_tag 'resort[resort_type]' ,'is_private', @resort.resort_type == "is_private", class: 'checkbox check-field inline', id: 'course_type_private' %>
              <span class="inline">Private</span>
            </div>
            <div class="inline">
              <%= check_box_tag 'resort[resort_type]' ,'is_semi_private', @resort.resort_type == "is_semi_private", class: 'checkbox check-field inline', id: 'course_type_semi_private' %>
              <span class="inline">Semi-Private</span>
            </div>
          </div>
          <div class="col-md-4">
            <%= label_tag :course_type ,'',class:"col-md-12 zero-left-right-padd", style: "min-height: 25px;" %>
            <%= select_tag('network', options_for_select(Network.all.pluck(:name, :id), @resort.network_id), options = {prompt: 'Network',class:'dropdown-padd dropdown form-control inline' , style: 'width:50%;' , name: 'resort[network_id]'}) %>
            <button type="button" class="btn btn-info btn-add" id='add-network' data-toggle="modal" data-target="#new_network">+</button>
            <%= link_to "Edit List", admin_networks_path %>
          </div>
          <div class="col-md-4 form-group">
            <%= label_tag :contact_info, 'Contact Info',class:"col-md-12 zero-left-right-padd"%>
            <%= f.text_field :website, class:"col-md-12 form-control contact-info check-field", placeholder: "Website" %>
            <%= f.text_field :phone_num, class:"col-md-12 form-control contact-info check-field", placeholder: "Phone Number" %>
          </div>
          <div class="col-md-8 form-group">
            <%= f.check_box :hide_logo %>
            <%= label_tag :hide_logo ,'Hide Logo'%>
          </div>
          <div class="col-md-8 form-group">
            <%= f.check_box :hide_about_course %>
            <%= label_tag :hide_about_course ,'Hide About Course Info'%>
          </div>
          <div class="col-md-8 form-group">
            <%= f.check_box :lead_generation %>
            <%= label_tag :lead_generation ,'Hide Lead Generation'%>
          </div>
          <div class="col-md-8 form-group"> 
            <%= f.check_box :hide_carousel %> 
            <%= label_tag :hide_carousel ,'Hide Carousel'%> 
          </div>  
          <div class="col-md-8 form-group"> 
            <%= f.check_box :hide_score_card %> 
            <%= label_tag :hide_carousel ,'Hide Score Card'%> 
          </div>

          <div class="col-md-8 form-group">
            <%= label_tag :fore_btn_text, 'FORE Button Text'%>
            <%= f.text_field :fore_btn_text, class:"col-md-12 form-control contact-info check-field"%>
          </div>

          <div class="col-md-8 form-group" style="display: none;">
            <%= f.text_field :fore_btn_background%>
          </div>

          <div class="col-md-8 form-group"> 
            <label for="fore_btn_background">FORE Button Background</label>
            <input type="color" id="fore_btn_background" name="fore_btn_background" value="<%= @resort.fore_btn_background.present? ? @resort.fore_btn_background : "#ff0000" %>">
          </div>

          <div class="col-md-8 form-group" style="display: none;">
            <%= f.text_field :fore_line_color%>
          </div>

          <div class="col-md-8 form-group"> 
            <label for="fore_line_color">FORE Line Color</label>
            <input type="color" id="fore_line_color" name="fore_line_color" value="<%= @resort.fore_line_color.present? ? @resort.fore_line_color : "#ff0000" %>">
          </div>

          <div class="col-md-6 form-group">
            <%= label_tag :custom_url, 'Custom URL',class:"col-md-12 zero-left-right-padd"%>
            <%= f.text_field :lead_url, class:"col-md-12 form-control contact-info check-field", placeholder: "Custom URL"%>
          </div>
          
          <div class = "col-md-6">
            <%= label_tag :logo, "Logo Image", class:"col-md-12 zero-left-right-padd "%>  
            <div class = "clearfix"></div>
            <div class="btn btn-success upload-btn">
              <div class = "logo-field">
                <%= f.file_field :logo, class: 'check-field logo-field'%>
              </div>

              <div class="cover image-division">
                <span class="close-cross hide">&times;</span>
                <%= image_tag("", class: "uploaded-cover-image course-create-image hide") %>
              </div>
            </div>
          </div>

          <div class="col-md-8 form-group">
            <h4>Embedable Link For Client</h4>
            <textarea style="height:90px; resize:none; padding: 10px; text-align: center; " readonly id="iframe_link" class="form-control">
              <div class="fore-test-iframe">
                <iframe src="<%= "#{request.base_url}/admin/resorts/#{@resort.id}/courses_list" %>" width="100%"  allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="height:270vh; border: none;" id="fore_videos_iframe" onload="resizeIframe(this)"> </iframe>
              </div>
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
              <script type="text/javascript" src="https://d1s5na5d5z3eyp.cloudfront.net/assets/iframeResizer.min.js"></script>
              <script type="text/javascript">
                iFrameResize({log: true, enablePublicMethods: true });
              </script>
            </textarea>
          </div>
          <div class="col-md-4 form-group">
            <button class="btn btn-primary" style="margin-top: 65px;" onclick="copyText()" type="button">Copy Link</button>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= f.submit "Save", class: "btn btn-primary", style: "margin-left:20px;", id: "save_client" %>
    </div>
  <% end %>
  <%= render :partial => 'admin/networks/new_modal' %>
</div>
<script type="text/javascript">
  function copyText() {
    /* Get the text field */
    var copyText = document.getElementById("iframe_link");

    /* Select the text field */
    copyText.select();

    /* Copy the text inside the text field */
    document.execCommand("copy");
  }

  $(".logo-field").change(function(){
    var imageDiv = $('.cover.image-division');
    if (this.files.length > 0) {
      var reader = new FileReader();
      reader.onload = function (e) {
        if (window.location.href.indexOf('edit') < 0){
          $('.uploaded-cover-image.course-create-image').attr('src', e.target.result).removeClass('hide');
          $(imageDiv).find('.close-cross').removeClass('hide');
        }else{
          if ($('.cover .resort-logo-image.cimage').length != 0){
            $('.cover .resort-logo-image.cimage').attr('src', e.target.result);
          }else{
            $(imageDiv).append("<span class='close-cross'>&times;</span> <img src='"+e.target.result+"' class='resort-logo-image cimage'>");
          }
        }
      }
      reader.readAsDataURL(this.files[0]);
    }
  });

  $("#fore_btn_background").change(function(){
    $("#resort_fore_btn_background").val(this.value)
  });

  $("#fore_line_color").change(function(){
    $("#resort_fore_line_color").val(this.value)
  });

</script>

app/views/admin/resorts/index.html.erb
<!-- Pre load vjs files for next page -->
<link href="//vjs.zencdn.net/6.2.8/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/6.2.8/video.min.js"> </script>
<script src="https://rawgit.com/atlance01/vrapp-ionic/master/www/js/lib/videojs-playlist.js"></script>


<div class="container">

<% content_for :side_nav do %>
  <%= render :partial => 'admin/shared/side_nav' %>
<% end %>

  <div class="panel panel-default">
    <h2>Clients List</h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <div id="course-search-form">
          <div class="col-md-3" style="padding:0px;">
            <%= form_for('', :url => url_for(:controller => 'search', :action => 'search') , method: "post", remote: true ) do |f|%>
              <%= text_field_tag :resort, "", class: "form-control", placeholder: "Search Clients", name: 'search[q]' %>
              <%= hidden_field_tag :klass, "resort", class: "form-control",name: 'search[klass]' %>
              <%= hidden_field_tag :id, "resorts-tbl", class: "form-control",name: 'search[id]' %>
            <%end%>
          </div>
          <div class="col-md-9">
          </div>
        </div>
        <table class="table table-striped" id="resorts-tbl">
          <thead>
            <tr>
              <th>Client Name</th>
              <th>Location</th>
              <th>Client Type</th>
              <th>No. of Courses</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @resorts.each do |resort| %>
              <tr>
                <td><%= link_to resort.name, admin_resort_courses_list_path(resort) %></td>
                <td><%= resort.try(:formated_location) %></td>
                <td><%= resort.try(:course_type) %></td>
                <td><%= resort.courses.count %></td>
                <td><%= link_to 'Edit', edit_admin_resort_path(resort) %> | <%= link_to 'Delete',admin_resort_path(resort) , method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Courses', admin_resort_courses_path(resort) %> </td>
                
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/admin/resorts/new.html.erb
<h1>New Resort</h1>

<%= render 'form', resort: @resort %>

<%= link_to 'Back', resorts_path %>

app/views/admin/resorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resort.name %>
</p>

<%= link_to 'Edit', edit_resort_path(@resort) %> |
<%= link_to 'Back', resorts_path %>